# example
stages:
  - name: Build something
    # Conditions for stages
    when:
      branch: master
      event: [ push, pull_request ]
    # Multiple steps run concurrently
    steps:
    - runScriptConfig:
        image: busybox
        shellScript: ls
stages:
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./nginx/deployment.yaml
stages:
- name: svc
  steps:
  - applyYamlConfig:
      path: ./nginx/svc.yaml

